# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: practicetest123
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bannerService

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-southeast-1
  environment:
    BUCKET_NAME: banner-image-bucket-sls
    TABLE_NAME: Banners
    REGION: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource:
        - arn:aws:s3:::banner-image-bucket-sls/*
        - arn:aws:dynamodb:ap-southeast-1:338175291532:table/Banners

resources:
  Resources:
    BannerImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: banner-image-bucket-sls
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
              AllowedOrigins:
                - '*'
    BannerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Banners
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: fileName
            AttributeType: S
        KeySchema:
          - AttributeName: fileName
            KeyType: HASH

functions:
  getAllBanners:
    handler: handlers/getAllBanners.getAllBanners
    events:
      - httpApi:
          path: /banners
          method: get
  getUploadUrl:
    handler: handlers/uploadBanner.getUploadUrl
    events:
      - httpApi:
          path: /upload-banner
          method: post
  confirmUpload:
    handler: handlers/confirmUpload.confirmUploadEventTrigger
    events:
      - s3:
          bucket: banner-image-bucket-sls
          event: s3:ObjectCreated:Put
          existing: true # This allows the function to be triggered by an existing object in the bucket
